### ISSUE TITLE
Batch Deposits

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-rootchain#17]
Pending deposits get stored in a queue. Upon a submit block from validator, all pending deposits get added first and then the submit block gets added first.

Concerns:
Storing deposits in queue may be expensive. Look into storing in memory vs storage

**Comment by hamdiallam** [comment]
The deposits can be put into a list and is simply cleared on each submitblock call

**Comment by colin-axner** [comment]
We may need to modifiy startExit() slightly. The only time it would matter is if a validator decided to be malicious by simply never submitting another block

**Comment by AdityaSripal** [comment]
@colin-axner there should be a seperate simple method to withdraw a pending deposit. This can be done immediately since all that is handled on the root contract.

@hamdiallam true, we still need to investigate the gas costs associated with that and how we might bring it down.

**Comment by AdityaSripal** [comment]
Closed. May conditionally reopen.
