### ISSUE TITLE
finalizeExit should not revert unintentionally.

### ISSUE THREAD

**Issue by hamdiallam** [FourthState/plasma-mvp-rootchain#20]
finalizeExit should not be required to process every single valid exit. Every iteration should check if enough gas is available to complete that one iteration and if not, return to avoid the the transaction from reverting. 

if the function reverts on for example the third iteration, the previous two successfully exited startExits will have to processed again.

**Comment by laskdaf** [comment]
There are a few ways to do this,
1. Keep track of gas usage, and terminate when there's not enough gas to processes the next loop (idea from Kelvin Fitcher).
2. Make the function have a set number of loops and give a recommended gas minimum to those who call the function. (Don't remember who came up with this idea, either Hamdi or Aditya)

**Comment by AdityaSripal** [comment]
The number of loops to iterate should be passed in as a parameter to function.

Maybe we should overload function to allow people to try and clear entire queue or if they want they can set the number of exits they're willing to process?

**Comment by laskdaf** [comment]
We can do that with option 1 then right? Just have the parameter be the amount of gas they put in.

**Comment by AdityaSripal** [comment]
It may be difficult to check how much gas a loop costs. It's easier to just define number of loops. Either way is fine tho.

**Comment by hamdiallam** [comment]
We could also just overestimate the gas cost for one loop iteration and use that as the threshold to continue the loop

**Comment by laskdaf** [comment]
No matter what we still need to estimate the gas cost so we can upperbound the gas cost of each loop

**Comment by AdityaSripal** [comment]
Is this closed now?

**Comment by laskdaf** [comment]
imo this feature is not critical.
