### ISSUE TITLE
Keep track of all previously withdrawn UTXOs

### ISSUE THREAD

**Issue by legengliu** [FourthState/plasma-mvp-rootchain#32]
In order to take care of the direct-descendant, double withdrawal attack (https://ethresear.ch/t/plasma-vulnerabiltity-sybil-txs-drained-contract/1654), keep a mapping of previously finalized exits (maybe priority => True/False) and allow someone to challenge an exit by proving that the exit's inputs have already been withdrawn.

**Comment by laskdaf** [comment]
Yes as of right now, some one could straight up repeatedly deposit, start exit, and finalize exit, and drain the contract.

**Comment by legengliu** [comment]
For any UTXO passed into startExit, calculate priority from its inputs; check to see if priority => Exit exists in both `finalizedExits` and `exits`.

**Comment by AdityaSripal** [comment]
Has this been solved? If so we should close
