### ISSUE TITLE
Change Deposit Handling

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-rootchain#36]
Since block ordering scheme won't work we need to change how deposits are handled.

Current idea: We add the deposits in during beginBlock. Will need to finalize sidechain design before changing rootchain.

**Comment by colin-axner** [comment]
Currently on the sidechain we have decided to replace Indenom1 and Indenom2 with DepositNum1 and DepositNum2. If the inputs corresponding DepositNum is 0 then it is a regular utxo. If it is non zero it corresponds to nth deposit. For example, if there have been n deposits on the rootchain, then the next deposit will have n +  1 deposit num. 

We can return blk numbering back to natural numbering (increment by 1) and separate deposits and utxo's. As far as withdrawing goes, we can use two separate queues. We can continue using the existing withdraw queue and add a second for deposit withdrawals. Deposit withdrawals can be given priority corresponding to their depositNum. 

We will need to think about what issues may arise with this idea.

**Comment by AdityaSripal** [comment]
We will implement solution #4 in plasma-research repo safeDeposits.md
