### ISSUE TITLE
Possibly Adjusting Deposit

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-rootchain#4]
Changes:
- Don't pass in txBytes
- Pass in address to deposit msg.value to 
- Pass in bool or use some type of flag to distinguish when the depositor will deposit to an address other than their own

Pros:
Allows for deposits to any address while adding a little user safety by using some type of flag. User doesn't need to construct the txBytes themselves. 

Cons:
Slightly more complexity and less clean.

A way to get around passing in txBytes is to build an on chain rlp encoder or as proposed on omisego/plasma-mvp in issue 65 make a deposit tx hash only be hash(address, value).

**Comment by AdityaSripal** [comment]
Why can't we just overload the deposit function. deposit() sends to msg.sender, deposit(address receiver) sends to receiver?

**Comment by colin-axner** [comment]
Yeah that sounds good, I wasn't sure if solidity functions supported overloading
