### ISSUE TITLE
Withdrawal Delay Attack

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-rootchain#42]
Currently, when processing exits we get the exit at the top of the priority queue. Since our priorities are determined by when the utxo was created on the child chain, it is possible to delay a majority of withdrawals from the child chain for a large amount of time. 

Assume probabilistic finality occurs in x blocks.
To delay for exits for up to a year, one would do the following. 
1. Deposit a small amount of eth
2. Every x blocks submit a transaction creating a 2 utxo's
3. repeat step 2 51 times with 1 of the created utxo's 

To prevent a majority of withdrawals for a year, submit an exit for your youngest utxo. Right before 1 week is up, submit a withdrawal for your next youngest utxo. In each case, the newer withdrawals will have a better priority and it's 1 week challenge period will start fresh. 

Possible Solutions:
- Allow users to finalize an exit by passing in their priority. If the corresponding exit is > 1 week, finalize it and add a flag to remove it from the pq once it is the min. 

- As per mvp spec, limit priorities to be no longer than the oldest block younger than 1 week old. Therefore a exit that is almost done with it's challenge period can never be put behind a exit that just started it's challenge period.

The second solution should be more efficient and will be easier to implement. Thoughts?

**Comment by colin-axner** [comment]
Expanding on the second solution: 

It could be implemented in the same way as OmiseGo, where you have a uint256 representing the priority.

- Left 128 Bits : `Math.max(childChain[txPos[0]].created_at + 2 weeks, block.timestamp + 1 weeks)`
- Right 128 Bits: `1000000000*txPos[0] + 10000*txPos[1] + txPos[2]`

I like this solution as all priorities within the queue would be unique. Then the question is, should the exit mapping be from position to exit with position being the right 128 bits or should it be from priority to exit with priority being the full 256 bits.

**Comment by laskdaf** [comment]
For the 2nd solution, would there be an issue of processing exit's out of order? 
In a mass exit due to the validator's invalid transaction, presumably all transactions afterwards can be assumed to be untrusted, so nobody will exit any of those. 
I'm not 100% sure that the fact that

**Comment by hamdiallam** [comment]
doesn't matter if you use the right 128bits or the full 256 bits. Would be unique either way for the mapping
