### ISSUE TITLE
Dynamic Input and Outputs for each Tx

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-rootchain#51]
Since with rlp you can encode/decode dynamic lists, I think we should support a variable number of inputs and outputs for each tx. 

Here is how we could represent these in the Msg of the Tx struct on the childchain.

Also, is the sender address still necessary?

```
type SpendMsg struct {
    Inputs    Inputs[]
    Outputs  Outputs[]
    Fee         uint64
}

type Input struct {
    Blknum uint64
    Txindex uint16
    Oindex uint8
    DepositNum uint64
    Address common.Address
}

type Output struct {
    Address common.Address
    Denom uint64
}

**Comment by AdityaSripal** [comment]
Sender address is still necessary because we need it for getSigners

**Comment by AdityaSripal** [comment]
Postponing this for later versions.
