### ISSUE TITLE
Rootchain Compatibility

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-rootchain#61]
Changes that need to be made:

- [x] CheckMembership()
When checking for the inclusion of a tx in a block, checkmembership should see if the sha256(txbytes) is included into the reported header for that block. The number of txs in a block will be variable and this should be taken into account. 

- [x] RLP Decoding
Currently the rootchain RLP decodes using the SpendMsg format on the side chain. This needs to be adjusted as the txbytes correspond to the [BaseTx struct](https://github.com/FourthState/plasma-mvp-sidechain/blob/6be0ef4c51b7718595de29c509df30b6ece51692/types/tx.go#L94). BaseTx has two fields, SpendMsg (actual plasma tx) and a Signature array. 

- [x] Switch to sha256 when hashing txbytes (note that tx sigs use keccak256)
see #21 

- [x] Confirmation Hash
Confirmation Hash should be `Keccak256(abi.encodePacket(txHash, blockHash))` . Hashing with sigs need to be deleted. 

- [x] Handling of Fees
Allow submitBlock() to accept the header (data hash) of a block and a fee associated with it.

**Comment by laskdaf** [comment]
@colin-axner @AdityaSripal It'd be nice it clarify exactly what's required. 
For example, I'm not to sure what you mean by "note that tx sigs use keccak256". Does it mean that tx sigs currently uses txbytes or that we need to use sha256 for txbytes but still use keccack256 for tx sigs.

**Comment by colin-axner** [comment]
We need to use sha256 for txbytes, since sha256 is used when forming a block with tendermint. However, we can still use keccack for making the confirmation hash and the sigHash. Does that make sense?

**Comment by colin-axner** [comment]
Confirm Signature Format will be changed on the sidechain. Rootchain does not need to change how it forms confirmation hashes
