### ISSUE TITLE
Bug in StartExit

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-rootchain#84]
Currently the fee in a block is the aggregate FeeAmounts of all UTXOs included in that block.

So if a block contains UTXOs A, B, C:

FeeUTXO has `amount = Fee(A) + Fee(B) + Fee(C)`

However, if input to A decides not to send confirm sigs and exits on rootchain. Then FeeUTXO amount does not change, even if one of its inputs, A is not valid.

The correct FeeUTXO amount in this scenario would be:
FeeUTXO has `amount = Fee(B) + Fee(C)`

Thus with current implementation, anytime any input to an included UTXO is successfully exited, the Fee for that block has an incorrect amount that will inflate the number of Ether in the sidechain.

Possible Solutions:

1) Have users commit to any fee they spent in a transaction (whether included or not) during StartExit so that they can exit `UTXO.Amount - AlreadySpentFee`
Then we also need a way to challenge an Exit by proving that a spend of the UTXO was included on sidechain with a Fee that is different from the claimed fee by user during startExit. (Note: No confirm sigs are necessary for this particular challenge)

2) Possibly others, but I think they will be more complicated than the above fix

**Comment by AdityaSripal** [comment]
The hard part is if there are 2 inputs to your transaction, which input does the fee come out of?

I think it's fair to say it comes out of the first input, and if `fee > Input1.Amount` then we take the rest out of the second input

**Comment by hamdiallam** [comment]
I think we should restrict the fee to the first input. It would reduce the number of potential challenges by the operator. If the fee is potentially taken from the second input, the validator would have to challenge both inputs if they ever exit. Restricting it to the first input only requires the operator to watch one input
