### ISSUE TITLE
Attack Vector in Deposit

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-rootchain#9]
A malicious validator can steal a depositor's funds.

Let’s say I want to deposit onto a child chain. I validate the child chain upto its most recent block (Block n). I submit a deposit transaction. A malicious validator sees my transaction in flight and produces an invalid block (Block n+1) by creating a UTXO out of thin air equal to my deposit. He can try to get his transaction processed by the root chain first by submitting the tx with a very high gasPrice. Thus, on the root chain his invalid block shows up before my deposit. Everyone exits with the UTXO’s from previous block. The validator’s fake UTXO can exit before mine, and he can steal my money.

Proposed solution: We keep track of the number of blocks that have been submitted by the validator (call this counter). When you deposit, you also pass in the last validator-submitted block you saw. In the case above, I pass in n as an argument to deposit. Inside deposit, if the argument is not equal to counter, then we reject the deposit. The depositor then sees the new submitted block and chooses if he still want to deposit in light of this new information. Since blocks can only be submitted by validators in 6-block intervals, this isn’t too much of a burden on a depositor.

**Comment by colin-axner** [comment]
Is this issue not fixed by having the rootchain increment block numbers? If deposit is called at block height n, then any call to submitBlock would be at n+1 and even if n+1 block got included on Ethereum's chain first, since we are using a mapping, as long as block n is eventually included the depositor should be able to get their money back right?

**Comment by AdityaSripal** [comment]
I don't think so. The deposit is not "called" at block height n. Before you deposit to a child chain, you have to validate its history.
So when a depositor validates up to block n, he puts his deposit transaction in the mempool. The malicious validator can then put an invalid block into the mempool at a higher gas price

Thus child chain mapping on root chain can get into two different states depending on what transaction gets processed by root chain first.

This situation is completely fine:
(n => (Valid Block)) (n + 1 => (Deposit Block)) (n + 2 => (Invalid Block))

This is a successful attack:
(n => (Valid Block)) (n + 1 => (Invalid Block)) (n + 2 => (Deposit Block))

**Comment by colin-axner** [comment]
Yeah you are right, for some reason I was thinking the state would be updated before included in a block. Do we need to add a counter variable? Couldn't the depositor pass in the block number they'd like to include it in and if it doesn't match the current block number then it is rejected? So if I go to deposit I pass in n + 1, then if the validator submits a block at n + 1, my deposit would be rejected.

**Comment by AdityaSripal** [comment]
The reason I want a variable that specifically tracks the validator-submitted blocks is that multiple deposits should be able to be added with no strict ordering between them.

If I go to deposit after seeing validator-submitted block n, and then 5 deposits get processed before mine does. My deposit should still go through because it is only a problem when an unseen validator-submitted block gets added before my deposit.

**Comment by colin-axner** [comment]
Yeah that makes sense. So counter would just be updated in submitBlock? We could probably add getCounter method too, but it shouldn't be necessary since participants should sync up with the child chain before depositing

**Comment by AdityaSripal** [comment]
I don't think we need getCounter. Since the validatorBlocks is a public variable, Solidity provides a getter method for it automatically.

**Comment by AdityaSripal** [comment]
Merged PR #11
